include:
  # ----------------------------
  # Direct (no dongle) - "bt"
  # ----------------------------
  - board: nice_nano
    shield: corne_left
    artifact-name: bt-corne-left
  - board: nice_nano
    shield: corne_right
    artifact-name: bt-corne-right

  # ----------------------------
  # Dongle central (Seeed XIAO nRF52840)
  # ----------------------------
  - board: xiao_ble
    shield: corne_dongle
    artifact-name: dongle-corne-xiao

  # Corne halves built as peripherals for the dongle
  - board: nice_nano
    shield: corne_left
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n -DCONFIG_ZMK_SPLIT_BLE_ROLE_PERIPHERAL=y
    artifact-name: dongle-corne-left
  - board: nice_nano
    shield: corne_right
    cmake-args: -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
    artifact-name: dongle-corne-right

  # ----------------------------
  # settings_reset (recommended to always build)
  # ----------------------------
  - board: nice_nano
    shield: settings_reset
    artifact-name: settings-reset-nice-nano
  - board: xiao_ble
    shield: settings_reset
    artifact-name: settings-reset-xiao
